name: "enterprise_dw"
version: "1.0.0"
config-version: 2
profile: "enterprise_dw"
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
log-path: "logs"
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  enterprise_dw:
    staging:
      +schema: bronze
      +materialized: view

    integration:
      +schema: integration
      +materialized: incremental

    marts:
      +schema: marts
      +materialized: table
